#!/usr/bin/env python
#
# Replace SSH based strawlab github logins with HTTPS based logins.
#
# This script is meant to be called from the base directory of a ROS
# install location. I.e. run:
#
#   ./replace_git_ssh_with_https
#
# from the directory with the setup.bash and .rosinstall file.
from __future__ import print_function
import glob, re, os

re_github_strawlab = re.compile(r'git@github.com:strawlab/')

def fix_fname(fname):
    inbytes = open(fname).read()
    outbytes = re_github_strawlab.sub('https://github.com/strawlab/',inbytes)
    if outbytes != inbytes:
        print('Fixing',fname)

        f2 = fname + '.https'
        with open(f2,mode='wb') as fd:
            fd.write(outbytes)
        os.rename( f2, fname )        

def main():
    files = glob.glob('*/.git/config') + ['.rosinstall']

    for fname in files:
        fix_fname(fname)

if __name__=='__main__':
    main()
